
package intendencia;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ParkingService", targetNamespace = "http://services/", wsdlLocation = "http://localhost:8080/Intendencia/Parking?wsdl")
public class ParkingService
    extends Service
{

    private final static URL PARKINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException PARKINGSERVICE_EXCEPTION;
    private final static QName PARKINGSERVICE_QNAME = new QName("http://services/", "ParkingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Intendencia/Parking?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARKINGSERVICE_WSDL_LOCATION = url;
        PARKINGSERVICE_EXCEPTION = e;
    }

    public ParkingService() {
        super(__getWsdlLocation(), PARKINGSERVICE_QNAME);
    }

    public ParkingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARKINGSERVICE_QNAME, features);
    }

    public ParkingService(URL wsdlLocation) {
        super(wsdlLocation, PARKINGSERVICE_QNAME);
    }

    public ParkingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARKINGSERVICE_QNAME, features);
    }

    public ParkingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ParkingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Parking
     */
    @WebEndpoint(name = "ParkingPort")
    public Parking getParkingPort() {
        return super.getPort(new QName("http://services/", "ParkingPort"), Parking.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Parking
     */
    @WebEndpoint(name = "ParkingPort")
    public Parking getParkingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services/", "ParkingPort"), Parking.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARKINGSERVICE_EXCEPTION!= null) {
            throw PARKINGSERVICE_EXCEPTION;
        }
        return PARKINGSERVICE_WSDL_LOCATION;
    }

}
