package services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-09-12T23:57:30.328-03:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://services/", name = "Parking")
@XmlSeeAlso({ObjectFactory.class})
public interface Parking {

    @WebMethod
    @RequestWrapper(localName = "parkingCancel", targetNamespace = "http://services/", className = "services.ParkingCancel")
    @ResponseWrapper(localName = "parkingCancelResponse", targetNamespace = "http://services/", className = "services.ParkingCancelResponse")
    @WebResult(name = "return", targetNamespace = "")
    public services.Credit parkingCancel(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1
    );

    @WebMethod
    @RequestWrapper(localName = "parkingSale", targetNamespace = "http://services/", className = "services.ParkingSale")
    @ResponseWrapper(localName = "parkingSaleResponse", targetNamespace = "http://services/", className = "services.ParkingSaleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public services.Sale parkingSale(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        long arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3
    );
}
